<?php

namespace AppBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByShop($shop){

        $qb = $this->createQueryBuilder('i');
        $qb->leftJoin('i.rack', 'r')
            ->where('r.shop =: SHOP')
            ->setParameter('SHOP',$shop);
        $result = $qb->getQuery()->getResult();

        return $result;

    }


}
